
#配置日志地址

logging:
  config: classpath:prod/logback-boot-prod.xml

spring:
  datasource:
    #MySQL 这个jar 包依赖类型默认是runtime，也就是说只有运行时生效，所以虽然这里报错，但是不影响代码运行。
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.131.242:3306/jks?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: lgy1997
  #springjpa生成表
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #不加这句则默认为生成myisam引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 0
    host: 47.107.131.242
    port: 6379
    password: lgy1997
    timeout: 5000
    #jedis:
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        max-idle: 5     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接

jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: Sans-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /swagger-resources/**,/v2/**,/webjars/**,/**/*.ico,/swagger-ui.html,/**/*.css,/**/*.jpg,/**/*.js,
    /index/**,/login/**,/test1/**,/system/**,/images/**,/**/*.jsx,

swagger2:
  enable: true

